// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPNc6i-jATy0QocL3CL5d38iG-8UCo4fE',
    appId: '1:533486029957:web:20eeef70dcad0ea079adec',
    messagingSenderId: '533486029957',
    projectId: 'yogasessions2',
    authDomain: 'yogasessions2.firebaseapp.com',
    storageBucket: 'yogasessions2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIGa2Gt10ah8X2G7KjKmaimvFuPtB043g',
    appId: '1:533486029957:android:463742000bcf553079adec',
    messagingSenderId: '533486029957',
    projectId: 'yogasessions2',
    storageBucket: 'yogasessions2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcrUudv01mK2OjAXM68l05Uk5FmYrBWE4',
    appId: '1:533486029957:ios:21d028b2c62c974d79adec',
    messagingSenderId: '533486029957',
    projectId: 'yogasessions2',
    storageBucket: 'yogasessions2.firebasestorage.app',
    iosBundleId: 'com.example.yogasessions',
  );

}